<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DesktopOps.Diagnostics\DesktopOps.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\DesktopOps.Updates\DesktopOps.Updates.csproj" />
    <ProjectReference Include="..\..\src\DesktopOps.Wpf\DesktopOps.Wpf.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
