from pathlib import Path

def resx(entries):
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<root>",
        '  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>',
        '  <resheader name="version"><value>2.0</value></resheader>',
        '  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>',
        '  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>',
    ]
    for k, v in entries:
        v = v.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        lines.append(f'  <data name="{k}" xml:space="preserve"><value>{v}</value></data>')
    lines.append("</root>")
    return "\n".join(lines) + "\n"

admin_en = [
("Nav_Overview","Overview"),("Nav_Programs","Programs"),("Nav_Groups","Groups"),("Nav_Assignments","Assignments"),("Nav_Releases","Releases"),("Nav_Rollouts","Rollouts"),
("Lead_Overview","Quick overview of programs, groups, releases, and assignments."),
("Lead_Programs","Create programs that can be assigned to groups and delivered by the agent."),
("Lead_Groups","Users in a group receive all programs assigned to that group. Optionally resolve SIDs and sync members from an AD/Windows group."),
("Lead_Assignments","Assign a program to a group — all members receive published releases."),
("Lead_Releases","Upload a ZIP and publish. Use rollout % to unlock only part of the assigned users."),
("Lead_Rollouts","Agent status messages after download and installation."),
("Status","Status"),("Recent","Recent"),("Actions","Actions"),("NoneYet","None yet"),
("PublishedReleases","Published releases"),("Draft","Draft"),("Published","Published"),
("UploadPublishRelease","Upload / publish release"),("OpenRollouts","Open rollouts"),
("DraftReleasesWaiting","{0} draft release(s) waiting to publish"),
("StagedRolloutsBelow","{0} staged rollout(s) below 100%"),
("CreateProgram","Create program"),("Name","Name"),("Slug","Slug"),("ShortName","Short name"),("Description","Description"),("Add","Add"),
("NoPrograms","No programs yet."),("CreateGroup","Create group"),("AdGroupOptional","AD group (optional)"),
("UsersCommaSeparated","Users (comma-separated)"),("NoGroups","No groups yet."),("NoDescription","No description"),
("Members","Members ({0}):"),("AddUser","Add user"),("AdWindowsGroup","AD/Windows group"),
("SyncFromAd","Sync from AD"),("ResolveSids","Resolve SIDs"),("DirectoryWindowsOnly","Directory services are only available on Windows."),
("PlaceholderAdGroup","DOMAIN\\Group"),("PlaceholderUsers","e.g. peke, alice"),
("PlaceholderUser","DOMAIN\\user or samAccountName"),("PlaceholderAdUsers","DOMAIN\\DesktopOps-Users"),
("GroupCreated","Group created ({0} member(s))."),
("UserAdded","User {0} added."),("UserAddedNoSid","User {0} added (no SID)."),
("AdGroupMissing","AD group name is missing."),
("NoMembersInAd","No members found in \"{0}\" (or group unreachable)."),
("AdSyncResult","AD sync \"{0}\": {1} new, {2} SID updated, {3} in AD."),
("NoSidsResolved","No new SIDs resolved."),("SidsResolved","{0} SID(s) resolved."),
("CreateAssignment","Create assignment"),("SelectProgram","Select program"),("SelectGroup","Select group"),("Assign","Assign"),
("NoAssignments","No assignments yet."),("Program","Program"),("Group","Group"),
("UploadRelease","Upload release"),("Version","Version"),("PackageZip","Package (ZIP)"),("ReleaseNotes","Release notes"),
("RolloutPercent","Rollout %"),("MandatoryUpdate","Mandatory update"),("Upload","Upload"),
("NoReleases","No releases yet."),("Size","Size"),("Rollout","Rollout"),("Publish","Publish"),
("Sha256","SHA-256"),("TimeUtc","Time (UTC)"),("User","User"),("Machine","Machine"),("Message","Message"),
("NoRolloutEvents","No rollout events yet."),("AuthOff","Auth off"),("Config","Config"),("Roles","Roles"),
("NoRoleClaims","no role claims"),("Reload","Reload"),("UnexpectedError","An unexpected error occurred."),
("ErrorTitle","Error"),("ErrorBody","An error occurred while processing your request."),
("NotFound","The page was not found."),("BackToOverview","Back to overview"),
("LoginRequired","Sign-in required (Windows authentication)."),
("Forbidden","You do not have permission for this page."),
("ForbiddenHint","Programs and releases require the Developer AD group. Groups and assignments require the Manager or Developer group."),
]

admin_de = [
("Nav_Overview","Übersicht"),("Nav_Programs","Programme"),("Nav_Groups","Gruppen"),("Nav_Assignments","Zuweisungen"),("Nav_Releases","Releases"),("Nav_Rollouts","Rollouts"),
("Lead_Overview","Kurzüberblick über Programme, Gruppen, Releases und Zuweisungen."),
("Lead_Programs","Programme anlegen, die Gruppen zugewiesen und vom Agent ausgeliefert werden."),
("Lead_Groups","Benutzer in einer Gruppe erhalten alle Programme, die dieser Gruppe zugewiesen sind. Optional: SID auflösen und Mitglieder aus einer AD-/Windows-Gruppe übernehmen."),
("Lead_Assignments","Programm einer Gruppe zuweisen – alle Mitglieder erhalten die veröffentlichten Releases."),
("Lead_Releases","ZIP hochladen und veröffentlichen. Mit Rollout-% nur einen Teil der zugewiesenen Benutzer freischalten."),
("Lead_Rollouts","Statusmeldungen der Agents nach Download und Installation."),
("Status","Status"),("Recent","Zuletzt"),("Actions","Aktionen"),("NoneYet","Noch keine"),
("PublishedReleases","Veröffentlichte Releases"),("Draft","Entwurf"),("Published","Veröffentlicht"),
("UploadPublishRelease","Release hochladen / veröffentlichen"),("OpenRollouts","Rollouts öffnen"),
("DraftReleasesWaiting","{0} Entwurf-Release(s) warten auf Veröffentlichung"),
("StagedRolloutsBelow","{0} gestaffelte(r) Rollout(s) unter 100 %"),
("CreateProgram","Programm anlegen"),("Name","Name"),("Slug","Slug"),("ShortName","Kurzname"),("Description","Beschreibung"),("Add","Hinzufügen"),
("NoPrograms","Noch keine Programme."),("CreateGroup","Gruppe anlegen"),("AdGroupOptional","AD-Gruppe (optional)"),
("UsersCommaSeparated","Benutzer (kommagetrennt)"),("NoGroups","Noch keine Gruppen."),("NoDescription","Keine Beschreibung"),
("Members","Mitglieder ({0}):"),("AddUser","Benutzer hinzufügen"),("AdWindowsGroup","AD-/Windows-Gruppe"),
("SyncFromAd","Aus AD synchronisieren"),("ResolveSids","SIDs auflösen"),("DirectoryWindowsOnly","Verzeichnisdienste nur unter Windows verfügbar."),
("PlaceholderAdGroup","DOMAIN\\Gruppe"),("PlaceholderUsers","z. B. peke, alice"),
("PlaceholderUser","DOMAIN\\user oder samAccountName"),("PlaceholderAdUsers","DOMAIN\\DesktopOps-Users"),
("GroupCreated","Gruppe angelegt ({0} Mitglied(er))."),
("UserAdded","Benutzer {0} hinzugefügt."),("UserAddedNoSid","Benutzer {0} hinzugefügt (ohne SID)."),
("AdGroupMissing","AD-Gruppenname fehlt."),
("NoMembersInAd","Keine Mitglieder in „{0}“ gefunden (oder Gruppe nicht erreichbar)."),
("AdSyncResult","AD-Sync „{0}“: {1} neu, {2} SID aktualisiert, {3} in AD."),
("NoSidsResolved","Keine neuen SIDs aufgelöst."),("SidsResolved","{0} SID(s) aufgelöst."),
("CreateAssignment","Zuweisung anlegen"),("SelectProgram","Programm wählen"),("SelectGroup","Gruppe wählen"),("Assign","Zuweisen"),
("NoAssignments","Noch keine Zuweisungen."),("Program","Programm"),("Group","Gruppe"),
("UploadRelease","Release hochladen"),("Version","Version"),("PackageZip","Paket (ZIP)"),("ReleaseNotes","Release Notes"),
("RolloutPercent","Rollout %"),("MandatoryUpdate","Pflicht-Update"),("Upload","Hochladen"),
("NoReleases","Noch keine Releases."),("Size","Größe"),("Rollout","Rollout"),("Publish","Veröffentlichen"),
("Sha256","SHA-256"),("TimeUtc","Zeit (UTC)"),("User","Benutzer"),("Machine","Rechner"),("Message","Meldung"),
("NoRolloutEvents","Noch keine Rollout-Ereignisse."),("AuthOff","Auth aus"),("Config","Konfig"),("Roles","Rollen"),
("NoRoleClaims","keine Role-Claims"),("Reload","Neu laden"),("UnexpectedError","Ein unerwarteter Fehler ist aufgetreten."),
("ErrorTitle","Fehler"),("ErrorBody","Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten."),
("NotFound","Die Seite wurde nicht gefunden."),("BackToOverview","Zur Übersicht"),
("LoginRequired","Anmeldung erforderlich (Windows-Authentifizierung)."),
("Forbidden","Keine Berechtigung für diese Seite."),
("ForbiddenHint","Für Programme und Releases wird die Developer-AD-Gruppe benötigt. Für Gruppen und Zuweisungen die Manager- oder Developer-Gruppe."),
]

agent_en = [
("TrayTooltip","DesktopOps Agent"),
("BalloonRunning","Running in the notification area. Right-click the blue D icon for options."),
("ServerUnreachableRetry","Server unreachable. Try again via search."),
("ServerUnreachable","Server unreachable."),
("UpdateAvailableOne","1 update available. Double-click or Search for updates…"),
("UpdateAvailableMany","{0} updates available. Double-click or Search for updates…"),
("LastSearchNone","Last search: –"),("LastSearch","Last search: {0}"),("Version","Version: {0}"),
("MenuConfiguration","Configuration"),("MenuSearchUpdates","Search for updates…"),
("MenuReinstall","Reinstall programs"),("MenuDiagnostics","Export diagnostics"),("MenuExit","Exit"),
("AgentStillStarting","Agent is still starting. Please wait."),
("NoUpdatesAvailable","No updates available."),
("ReinstallConfirm","Remove local program installs and search again?\n(The agent itself is kept.)"),
("ReinstallTitle","Reinstall programs"),
("NothingToReinstall","No programs found to reinstall."),
("DiagnosticsExported","Diagnostics exported to {0}"),
("AgentUpdateRestart","Agent update prepared. Restarting…"),
("SearchTitle","DesktopOps – Search for updates"),("Searching","Searching for updates…"),("Cancel","Cancel"),
("NoUpdatesFound","No updates found."),
("UpdateTitle","DesktopOps – Updates"),("PendingActions","The following actions are pending:"),
("Execute","Execute"),("Close","Close"),("NoPendingActions","No pending actions."),
("ActionsReady","{0} action(s) ready."),("ProgressStep","{0} / {1} – {2}: {3}"),
("NothingInstalled","Nothing installed."),("ActionsDone","{0} action(s) completed."),("Cancelled","Cancelled."),
("ConfigTitle","DesktopOps – Configuration"),("Save","Save"),("TabGeneral","General"),("TabPrograms","Programs"),
("InstallFolder","Installation folder"),("LastSearchLabel","Last search"),("SearchEllipsis","Search…"),
("AgentVersion","Agent version"),
("AutoInstall","Install updates automatically at startup"),
("NotifyUpdates","Notify when updates are found"),
("NoSearchYet","No search yet"),
("ColName","Name"),("ColLatest","Latest version"),("ColInstalled","Installed version"),
("ActionInstall","{0} - Install"),("ActionInstallVer","{0} - {1} - Install"),
("ActionUpdate","{0} - Update"),("ActionUpdateVer","{0} - {1} - Update"),
("ActionUninstall","{0} - Uninstall"),
("ProgressPreparing","Preparing…"),("ProgressAgentPreparing","Preparing agent update…"),
("ProgressRestart","Scheduling restart…"),("ProgressRemoving","Removing…"),
("ProgressBackup","Creating backup…"),("ProgressDownload","Download…"),
("ProgressInstall","Installation…"),("ProgressFailed","Failed"),("ProgressDone","Done"),
]

agent_de = [
("TrayTooltip","DesktopOps Agent"),
("BalloonRunning","Läuft im Infobereich. Rechtsklick auf das blaue D-Symbol für Optionen."),
("ServerUnreachableRetry","Server nicht erreichbar. Erneuter Versuch über die Suche."),
("ServerUnreachable","Server nicht erreichbar."),
("UpdateAvailableOne","1 Aktualisierung verfügbar. Doppelklick oder „Updates suchen…“."),
("UpdateAvailableMany","{0} Aktualisierungen verfügbar. Doppelklick oder „Updates suchen…“."),
("LastSearchNone","Letzte Suche: –"),("LastSearch","Letzte Suche: {0}"),("Version","Version: {0}"),
("MenuConfiguration","Konfiguration"),("MenuSearchUpdates","Updates suchen…"),
("MenuReinstall","Programme neuinstallieren"),("MenuDiagnostics","Diagnose exportieren"),("MenuExit","Beenden"),
("AgentStillStarting","Agent startet noch. Bitte kurz warten."),
("NoUpdatesAvailable","Keine Updates verfügbar."),
("ReinstallConfirm","Lokale Programm-Installationen entfernen und neu suchen?\n(Der Agent selbst bleibt erhalten.)"),
("ReinstallTitle","Programme neuinstallieren"),
("NothingToReinstall","Keine Programme zum Neuinstallieren gefunden."),
("DiagnosticsExported","Diagnose exportiert nach {0}"),
("AgentUpdateRestart","Agent-Update vorbereitet. Neustart…"),
("SearchTitle","DesktopOps – Updates suchen"),("Searching","Updates werden gesucht…"),("Cancel","Abbrechen"),
("NoUpdatesFound","Keine Updates gefunden."),
("UpdateTitle","DesktopOps – Updates"),("PendingActions","Folgende Aktionen stehen aus:"),
("Execute","Ausführen"),("Close","Schließen"),("NoPendingActions","Keine ausstehenden Aktionen."),
("ActionsReady","{0} Aktion(en) bereit."),("ProgressStep","{0} / {1} – {2}: {3}"),
("NothingInstalled","Nichts installiert."),("ActionsDone","{0} Aktion(en) ausgeführt."),("Cancelled","Abgebrochen."),
("ConfigTitle","DesktopOps – Konfiguration"),("Save","Speichern"),("TabGeneral","Allgemein"),("TabPrograms","Programme"),
("InstallFolder","Installationsordner"),("LastSearchLabel","Letzte Suche"),("SearchEllipsis","Suchen…"),
("AgentVersion","Agent-Version"),
("AutoInstall","Updates beim Start automatisch installieren"),
("NotifyUpdates","Benachrichtigen, wenn Updates gefunden wurden"),
("NoSearchYet","Noch keine Suche"),
("ColName","Name"),("ColLatest","Neueste Version"),("ColInstalled","Installierte Version"),
("ActionInstall","{0} - Installieren"),("ActionInstallVer","{0} - {1} - Installieren"),
("ActionUpdate","{0} - Aktualisieren"),("ActionUpdateVer","{0} - {1} - Aktualisieren"),
("ActionUninstall","{0} - Deinstallieren"),
("ProgressPreparing","Vorbereitung…"),("ProgressAgentPreparing","Agent-Update wird vorbereitet…"),
("ProgressRestart","Neustart wird geplant…"),("ProgressRemoving","Wird entfernt…"),
("ProgressBackup","Backup wird erstellt…"),("ProgressDownload","Download…"),
("ProgressInstall","Installation…"),("ProgressFailed","Fehlgeschlagen"),("ProgressDone","Fertig"),
]

root = Path(__file__).resolve().parents[1]
(root / "src/DesktopOps.Admin/Resources").mkdir(parents=True, exist_ok=True)
(root / "src/DesktopOps.Agent/Resources").mkdir(parents=True, exist_ok=True)
(root / "src/DesktopOps.Admin/Resources/Ui.resx").write_text(resx(admin_en), encoding="utf-8")
(root / "src/DesktopOps.Admin/Resources/Ui.de.resx").write_text(resx(admin_de), encoding="utf-8")
(root / "src/DesktopOps.Agent/Resources/Strings.resx").write_text(resx(agent_en), encoding="utf-8")
(root / "src/DesktopOps.Agent/Resources/Strings.de.resx").write_text(resx(agent_de), encoding="utf-8")
print("ok", len(admin_en), len(agent_en))
